### ISSUE TITLE
eigen repo is deleted

### ISSUE THREAD

**Issue by hubutui** [Xtra-Computing/thundersvm#105]
Hey, it seems the [eigen](https://github.com/RLovelett/eigen.git) is deleted. So, could we use other repo? Say eigen from system? There is a eigen package in Ubuntu or some other Linux distribution's official repo.

**Comment by GODqinbin** [comment]
The eigen repo is a submodule. You can use the following instruction in the ThunderSVM repo to download:
`git submodule init eigen && git submodule update`
The source has not been deleted. You can refer to [https://thundersvm.readthedocs.io/en/latest/how-to.html](the doc). Thanks.

**Comment by hubutui** [comment]
Sorry, I git clone this repo days ago, at that time, eigen submodule referred to [this broken url](https://github.com/RLovelett/eigen).
