### ISSUE TITLE
thundersvm-predict out of memory

### ISSUE THREAD

**Issue by taotao033** [Xtra-Computing/thundersvm#107]
I have tried -m to set,but it still don't work. 
Throw an error: FATAL [default] out of memory, ...
Fatal log at [.../thundersvm-predict.cpp:74]
Aborted (core dumped)
Please , help ! Thank you !

**Comment by taotao033** [comment]
My test set size is 54MB .I tried splitting the test set before,fortunately it work,but It's verbose.Please help me .Please!

**Comment by zeyiwen** [comment]
Would you share your dataset, and the parameters for training SVMs? Please keep in mind that if we can't reproduce the problem you reported, we can't fix the problem.

**Comment by GODqinbin** [comment]
We have just fixed a bug on the memory size. Can you update the code and try again? If the problem still exists, please share your dataset and commend so that we can debug it. Thanks.

**Comment by taotao033** [comment]
> We have just fixed a bug on the memory size. Can you update the code and try again? If the problem still exists, please share your dataset and commend so that we can debug it. Thanks.

Nice,well done ! it work fine !  My problem has been solved. Thanks a lot !
