### ISSUE TITLE
How to modify the evaluation metric? 

### ISSUE THREAD

**Issue by wywywy01** [Xtra-Computing/thundersvm#108]
您好:
   系统环境:ubuntu16.04,  cuda-9.0, cudnn7, matlab2017a   
   我在上面环境下运行你的代码,但是想要修改成其他的评价指标,我该怎么做呢?谢谢了

**Comment by GODqinbin** [comment]
如果你熟悉scikit-learn，你可以使用我们的scikit接口，里面可以自己定义评价指标。
如果想用matlab接口，在svm_interface_api.cpp文件中第88行和第156行是我们定义的评价指标，分别对应thundersvm train和predict，你可以替换成你的，代码中predict_y是我们预测的label值。

**Comment by wywywy01** [comment]
好的，我修改了svm_interface_api.cpp里面的代码。比如说在88行前面加一行：
LOG(INFO) << "  test" ;
然后 在build 下面 make -j，重新运行程序，但是没有对应的打印信息，所以请教下如何使改动生效呢？

**Comment by wywywy01** [comment]
> Would you please ask the question in English? Please also share the hyper-parameters, the command to run ThunderSVM, the output of the program, etc., such that we can reproduce the problem.
I use the example code int this page  [https://github.com/XtraComputing/thundersvm/tree/master/Matlab](url);  and i want to modify the metric ,so i  try to add  a test code in thundersvm/src/svm_interface_api.cpp line 88 like this :
![image](https://user-images.githubusercontent.com/22450352/48458542-cacf6180-e801-11e8-9cb3-432da5beec92.png)
and then i  make -j in thundersvm/build dir, when i rerun above code,the LOG in line 88  does not appeared?  how can i make the modify  valid,3x?

**Comment by GODqinbin** [comment]
I tried the same code and it works. Did you see the other output in your matlab window? A possible problem is that the output doesn't show in your Matlab.

**Comment by wywywy01** [comment]
> I tried the same code and it works. Did you see the other output in your matlab window? A possible problem is that the output doesn't show in your Matlab.
 Thanks a lot ! It works now.
 i modify svm_interface_api.cpp ,
and then make -j in build dir, 
and restart my matlab , finally rerun it.
