### ISSUE TITLE
Package and upload on Pypi

### ISSUE THREAD

**Issue by louisabraham** [Xtra-Computing/thundersvm#111]
It would be great if the installation was simpler. For example, providing the package via pypi would be very convenient.

**Comment by zeyiwen** [comment]
Thanks for the comments! We will add this functionality, but it may take some time due to the limitation of manpower. In fact, enabling ```pip install``` requires building various of libraries for different platforms and different versions of cuda, which probably requires significant amount of effort.

**Comment by zeyiwen** [comment]
ThunderSVM now supports ```pip install```. Please check it out from the thundersvm GitHub page.

**Comment by louisabraham** [comment]
Awesome!
