### ISSUE TITLE
How to enable GPUs for training and predicting with SvmModel class in python

### ISSUE THREAD

**Issue by yichen-um** [Xtra-Computing/thundersvm#112]
Dear all,

I'm currently working on a classification problem and is looking for ways to speed up my SVMs classifier training and predicting, which is currently implemented using CPU + LIBSVM and wrapped in Python with sklearn package. More specifically I'm looking for ways of using Nvidia GPUs to perform the training and prediction. I came across your work at the Github and read your paper, which is very interesting, and I'm wondering if there is any way that I can implement the following SVC training and prediction with GPUs. Please find below a example of my code to illustrate this question:

----------------------------------------------example of my code------------------------------------
import thundersvmScikit as svm
#### train model
clf = svm.SVC(kernel='linear', probability=True, class_weight = weight)
clf.fit(x, label)   <====== (how do I use GPUs here?)
clf.save_to_file('./clf_folder')
..........

#### make predictions with trained model
clf.load_from_file('./clf_folder')
y_pred = clf.predict([x])[0] . <====== (how do I use GPUs here?)
........
---------------------------------------------end of example------------------------------------------

I looked your Python wrapper and it seems now it does not provide API/argument for using GPUs for the SVC class, unless I missed something.

Finally, I really appreciate your time reading it, and I can also post my question in the github as well if you think it will be helpful to others. I look forward to hearing from you.

Kind regards,

Yi

**Comment by GODqinbin** [comment]
The python wrapper will call the ThunderSVM shared library. If you build the library with GPU (by default), the python wrapper also uses GPU. For the codes using GPUs, you can check the *.cu files under the "src/thundersvm/kernel" directory. Thanks.
