### ISSUE TITLE
OSError Windows Error 0xe06d7363                              

### ISSUE THREAD

**Issue by adizhol** [Xtra-Computing/thundersvm#115]
Windows 10 64bit
python 3.6
CUDA 8.0
Visual Studio 2015

compiled from source

```
from thundersvmScikit import OneClassSVM

clf = OneClassSVM(nu=1e-4, kernel="rbf",max_iter =100,verbose = True, gpu_id=0)
clf.fit(X_all.reshape(-1,32))

```
X_all is Nx32xMxN

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-48-46355c01b3f3> in <module>
      4 
      5 clf = OneClassSVM(nu=1e-4, kernel="rbf",max_iter =100,verbose = True, gpu_id=0)
----> 6 clf.fit(X_all.reshape(-1,32))
      7 # y_pred_train = clf.predict(X_train)
      8 y_pred_test = clf.predict(encoding_threat.reshape(-1,32))

c:\users\owner\appdata\local\conda\conda\envs\allegro_env\lib\site-packages\thundersvm-github_master-py3.6.egg\thundersvmScikit.py in fit(self, X, y)
    440 
    441     def fit(self, X, y=None):
--> 442         super(OneClassSVM, self).fit(X, np.ones(_num_samples(X)))
    443 
    444 class SVR(SvmModel, RegressorMixin):

c:\users\owner\appdata\local\conda\conda\envs\allegro_env\lib\site-packages\thundersvm-github_master-py3.6.egg\thundersvmScikit.py in fit(self, X, y)
    104         fit = self._sparse_fit if self._sparse else self._dense_fit
    105         self.model = thundersvm.model_new(solver_type)
--> 106         fit(X, y, solver_type, kernel)
    107         if self._train_succeed[0] == -1:
    108             print ("Training failed!")

c:\users\owner\appdata\local\conda\conda\envs\allegro_env\lib\site-packages\thundersvm-github_master-py3.6.egg\thundersvmScikit.py in _dense_fit(self, X, y, solver_type, kernel)
    174             self.verbose, self.max_iter, self.n_jobs, self.max_mem_size,
    175             self.gpu_id,
--> 176             n_features, n_classes, self._train_succeed, c_void_p(self.model))
    177         self.n_features = n_features[0]
    178         self.n_classes = n_classes[0]

OSError: [WinError -529697949] Windows Error 0xe06d7363

**Comment by GODqinbin** [comment]
Can you share your commands to build the library? We tried the same environment (Win10 64 bit, python 3.6.7, cuda 8.0, VS 2015) and it works fine. There may be some errors when you built the library.

**Comment by adizhol** [comment]
Hi,
It appears the error was due to out-of memory in the GPU.
