### ISSUE TITLE
ThunderSVM performance using Scikit interface

### ISSUE THREAD

**Issue by zutron** [Xtra-Computing/thundersvm#123]
Hi,

I'm trying to use ThunderSVM via the scikit python interface to run a regression grid search on my gpu.

The following code:

```
GridSearchCV(SVR(), tuned_parameters, cv=10, n_jobs = 2,verbose=3,
				   scoring='neg_mean_squared_error', error_score='raise')
```

Throws an error when n_jobs is set to more than 1.  The error thrown is 

```
 File "C:\Users\XXXX\XXXX\Scikit\thundersvm-master\python\thundersvmScikit.py", line 85, in fit
    thundersvm.model_free(c_void_p(self.model))
OSError: exception: access violation reading 0x00000162F65A2410
```

I seem to be able to run multiple instances using the compiled executable (as long as I control the memory usage with -m), but using the scikit interface I get a near instant crash.

Specs: Windows 10, rtx2080, 9900k, 32gb ram.

Datasets I've tried are 10 or 100 features, with about 400k examples.

**Comment by GODqinbin** [comment]
Hi,
We have fixed the bug. You can update the library and try again. If n_jobs > 1 in GridSearchCV(), it calls multiple fix() functions, which is not compatible with our previous code. By the way, our interface provides the n_jobs parameter. For example, you can also use the following code:
```
GridSearchCV(SVR(n_jobs = 2), tuned_parameters, cv=10, verbose=3,
				   scoring='neg_mean_squared_error', error_score='raise')
```

**Comment by zeyiwen** [comment]
The issue should be resolved now, so we like to close it.

**Comment by zutron** [comment]
Confirmed working over here! Great job!
