### ISSUE TITLE
Scikit interface argument erroneously named "decison_function_shape"

### ISSUE THREAD

**Issue by wirawan0** [Xtra-Computing/thundersvm#124]
Hi,

I discovered that the scikit-learn interface (SVC class) has an argument that has a typo: it is named `decison_function_shape` instead of `decision_function_shape`. It is missing one `i`. Could you fix that to not break compatibility with scikit-learn?

Thanks,
Wirawan

**Comment by GODqinbin** [comment]
Hi,

Sorry for the typo. We just fixed it. Thanks for your feedback.

**Comment by zeyiwen** [comment]
The typo should be fixed now, so we like to close this issue.
