### ISSUE TITLE
Training Killed

### ISSUE THREAD

**Issue by readicculus** [Xtra-Computing/thundersvm#127]
Trying to train using a 6gb file.  I have 32gb RAM and 11gb GPU.  When training is "Killed" I am nowhere near my max memory usage limits but cpu is working pretty hard, 100% on 3 cores.  It works fine on a smaller 3gb subset of the data.

Here is the log:
```
2019-02-23 19:29:51,124 INFO [default] loading dataset from file "/data/training_sets/thundersvm/train_128_160.txt"
2019-02-23 19:30:33,198 INFO [default] #instances = 19328, #features = 20479
2019-02-23 19:30:33,204 INFO [default] training C-SVC
2019-02-23 19:30:33,204 INFO [default] C = 10
2019-02-23 19:30:33,204 INFO [default] gamma = 0.001
2019-02-23 19:30:34,305 INFO [default] 5 fold cross-validation (1/5)
Killed

```

It's not me accidentally killing the process I've tried training this dataset multiple times and get same issue every time

**Comment by zeyiwen** [comment]
Would you share the data set? We cannot reproduce the issue, given this information. Also, please share the command line options you used.

**Comment by readicculus** [comment]
Command used, in last post had -v 5, but gets killed even without:
`./bin/thundersvm-train -t 2 -c 10  -g 0.001 /data/training_sets/thundersvm/train_128_160.txt `


[Train file(5.7GB)](https://drive.google.com/file/d/13-nWWgJ_cK5AesrYCrc54jjyvqBQ2j6t/view?usp=sharing)

**Comment by shijiashuai** [comment]
Hi. I tested the dataset on a 256GB memory + 12GB GPU memory machine. It works fine. And the peak memory usage is about 19G on host and 3.5G on device. It should works on your machine. I'm trying to find some other problems..

**Comment by readicculus** [comment]
ah maybe thats it It wasn't even close when it crashed which is confusing but I only have 16gb ram memory and you said it peaked at 19gb?  Maybe its ram and htop is messed up.  Anyways I've got another 16gb in the mail arriving in 2 days so should be able to test this out again with 32gb ram and I'll updated the thread.

**Comment by zeyiwen** [comment]
The thread is inactive... It seems the problem has been solved.
