### ISSUE TITLE
Missing attribute for SVC

### ISSUE THREAD

**Issue by fuzzyBatman** [Xtra-Computing/thundersvm#128]
The coef_ attribute that is available in the SVC module in scikit_learn is missing in thundersvm?

Initialised as
`clf = SVC(kernel='linear')`

Calling `clf.coef_` post training results in
> AttributeError: 'SVC' object has no attribute 'coef_'

**Comment by GODqinbin** [comment]
Hi, @fuzzyBatman 

We just added the coef_ attribute. You can have a try. Thanks.

**Comment by fuzzyBatman** [comment]
Hi, @GODqinbin 

Thank you for the quick response. It works as it should :D
