### ISSUE TITLE
about cublasGemmEx

### ISSUE THREAD

**Issue by SubjectNoi** [Xtra-Computing/thundersvm#129]
Hello, I changed the matrix API in kernelmatrix_kernel.cu, using cublasGemmEx, feed with origin input rather than csr matrix, and I extend the training set from 150 to 30000. After that I compare the performance between cublasGemmEx with origin cusparseScsrmm2，I experienced a 10% improvement. (By calculate the time for training)

**Comment by zeyiwen** [comment]
Sounds cool. Would you open a pull request? We will review the code, and see if it can be merged into the project.
