### ISSUE TITLE
Output Generation Source Code Files [Question]

### ISSUE THREAD

**Issue by Ben1Mo** [Xtra-Computing/thundersvm#130]
I'm new to ThunderSVM and I'm sorry if the question is repeated or stupid. I was about to explore the code, in this phase, I searched for the output generated by the trainer in many ".cpp" files in the src/thundersvm directory and other directories too, I can find some output lines like the "number of features", "training finished"...etc but I didn't seem to find the global iterations and total local iterations, I want to know exactly where I can find them in order to understand more their role and how they are generated and also to make some modifications, I should note that I already read issue #122  of
@naveenmiriyalu and the answers of @shijiashuai and @zeyiwen and I understand theoretically what these outputs mean.
Thank you!

**Comment by GODqinbin** [comment]
Hi, @Ben1Mo . The global iterations and local iterations are in "csmosolver.cpp" file under "src/thundersvm/solver" directory. More specifically, they are in line 104 and line 113 of "csmosolver.cpp".

**Comment by Ben1Mo** [comment]
Hi @GODqinbin , Thank you, yep I found them, I'm also curious about how I can change the "the working set size", I'm using an Nvidia Tesla P100 with 12GB memory and I'm aware that this GPU can allow me to change that to 1024 working set size (max) but every time I get different value in the Output, I want to understand how this number changes through various training, is it related to the svm type, kernel type ? or is these differences related to the GPU and how it allocates computing blocks ?

**Comment by zeyiwen** [comment]
Please read our papers, the SMO algorithm for SVM training, and also some basics about CUDA programming...
