### ISSUE TITLE
Broken link to API Reference (doxygen)

### ISSUE THREAD

**Issue by miguelangel** [Xtra-Computing/thundersvm#136]
Hi,

When clicking on the [API Reference (doxygen)](http://zeyiwen.github.io/thundersvm/) link that can be found in the [README.md](https://github.com/Xtra-Computing/thundersvm/blob/master/README.md), a 404 error page is displayed.

Hope it helps.

Regards,
Miguel

**Comment by zeyiwen** [comment]
Thanks! Should work now.
