### ISSUE TITLE
The GPU memory doesn't release after the model training is finished.

### ISSUE THREAD

**Issue by ZesenChen** [Xtra-Computing/thundersvm#137]
Hello. I used multiprocessing for thundersvm training for multi-lablel problem. However, after some models training are finished, the memory of GPU didn't release. Can anyone give me some advice?

**Comment by zeyiwen** [comment]
Which interface do you use? Would you construct a minimum example for us to reproduce the problem?

**Comment by zeyiwen** [comment]
Not active... So I like to close it.
