### ISSUE TITLE
SVC sv indices

### ISSUE THREAD

**Issue by berryweinst** [Xtra-Computing/thundersvm#138]
Hi,
In Sklearn SVC we had access to the sv indices (model.support_). How can one extract them from the Thunder model?

Thanks.

**Comment by GODqinbin** [comment]
Hi @berryweinst 

We have added the attribute support_. You can update the code and try again. Thanks.

**Comment by berryweinst** [comment]
Thank you so much for the quick response and the enhancement. Can I ask to update the wheel file as well please? 
thundersvm-cu90-0.2.0-py3-none-linux_x86_64.whl

**Comment by jiahuanluo** [comment]
Hi @berryweinst , I have uploaded a new version wheel file to PYPI, you can use `pip install thundersvm` for Linux with Cuda 9.0 and Python3.

Cheers,
Locke

**Comment by berryweinst** [comment]
Thank you so much. Seem to work very well.
