### ISSUE TITLE
Not even working for me in jupyter

### ISSUE THREAD

**Issue by infoankit10** [Xtra-Computing/thundersvm#140]
I am trying to use it on (5000, 3009) shape dataset in jupyter notebook. Jupyter kernel gets failed, although its working fine with sklearn svm.SVC method.
Any quick solution? 

```
#### This code not working ####
start = time. time()
clf = SVC(kernel='linear')
clf.fit(X_train, Y_train)
end = time. time()
print(end-start)
```

```
#### This code working fine ####
start = time. time()
clf = svm.SVC(kernel='linear')
clf.fit(X_train, Y_train)
end = time. time()
print(end-start)
```

Actually, my overall data set is very large. Its shape is around (150000, 3009). So I am looking if your package can provide better performance.

Regards,
Ankit Aggarwal

**Comment by zeyiwen** [comment]
We have tried thundersvm on jupyter nodebook, and it works fine... Please provide a minimum example for us to reproduce your issue.
