### ISSUE TITLE
[Python] Support balanced weights?

### ISSUE THREAD

**Issue by dourouc05** [Xtra-Computing/thundersvm#141]
scikit-learn supports `class_weight=‘balanced’` (https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html), in which case it deals with the computation of the weights. However, in thundersvm, using this option yields an error. (Which is known: #91.)

Would you be interested in a patch to support this?

**Comment by GODqinbin** [comment]
Hi @dourouc05 ,

We have added the function in the newest library. You can update the code and try it. Thanks.

**Comment by dourouc05** [comment]
Thanks for your reactivity :)!
