### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by feynman233** [Xtra-Computing/thundersvm#142]
Hi, when I use the linear kernel for a large dataset in  pycharm，the code ends at "Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)", but rbf kernel is just Ok, how can I fix this? thanks very much !
My gpu is titanxp and the cuda version is 9.0

**Comment by jiahuanluo** [comment]
Hi, @feynman233,
We have tested our newest code on some large datasets and it works fine.
You can try it with the newest code.
BTW, the wheel file listed on Readme.md may not be updated timely. 
If you are using `pip install`, you can update your package with `pip install thundersvm==0.3.1`, the newest version, or you can build it from the source.

Thanks

**Comment by feynman233** [comment]
Thanks! By the way, where can I find the newest release version from `pip install`, because there are no update histories on the github page.

**Comment by feynman233** [comment]
@jiahuanluo Thanks! By the way, where can I find the newest release version from `pip install`, because there are no update histories on the github page.

**Comment by jiahuanluo** [comment]
We will put it on our github page and you can find it [here](https://github.com/Xtra-Computing/thundersvm/releases) next.

**Comment by feynman233** [comment]
@jiahuanluo thanks very much!
