### ISSUE TITLE
it is not loading dll of cuda [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by dileep3004** [Xtra-Computing/thundersvm#144]
Traceback (most recent call last):
  File "thundersvm1.py", line 20, in <module>
    from thundersvm import SVC
  File "C:\Users\pc\AppData\Local\Programs\Python\Python36\lib\site-packages\thundersvm\__init__.py", line 12, in <module>
    from .thundersvmScikit import *
  File "C:\Users\pc\AppData\Local\Programs\Python\Python36\lib\site-packages\thundersvm\thundersvmScikit.py", line 41, in <module>
    thundersvm = CDLL(lib_path)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

**Comment by jiahuanluo** [comment]
Hi @dileep3004 

Did you try the latest library? We have tested our library and it works fine in Windows. It seems that your system lacks some dependencies. We cannot figure out the problem according to your information.

**Comment by Yiyiyimu** [comment]
Same problem occurs on both cpu and cuda10 version.

**Comment by jiahuanluo** [comment]
@Yiyiyimu Thank you for your information. 

I have tested our latest version on Windows with CUDA 10, and it works fine.
Could you please provide more detail to help us fix this efficiently?

Thanks.

**Comment by 5james** [comment]
Hi,
I have similar issue with CUDA 10 on linux.

During cmake I got warnings:

> In file included from /home/user11/thundersvm/include/thundersvm/thundersvm.h:13:0,
>                  from /home/user11/thundersvm/include/thundersvm/syncmem.h:8,
>                  from /home/user11/thundersvm/src/thundersvm/syncmem.cpp:5:
> /home/user11/thundersvm/src/thundersvm/syncmem.cpp: In destructor ‘thunder::SyncMem::~SyncMem()’:
> /home/user11/thundersvm/include/thundersvm/util/common.h:37:65: warning: throw will always call terminate() [-Wterminate]
>      if(error == cudaErrorMemoryAllocation) throw std::bad_alloc(); \
>                                                                  ^
> /home/user11/thundersvm/src/thundersvm/syncmem.cpp:29:17: note: in expansion of macro ‘CUDA_CHECK’
>                  CUDA_CHECK(cudaFree(device_ptr));
>                  ^~~~~~~~~~
> /home/user11/thundersvm/include/thundersvm/util/common.h:37:65: note: in C++11 destructors default to noexcept
>      if(error == cudaErrorMemoryAllocation) throw std::bad_alloc(); \
>                                                                  ^
> /home/user11/thundersvm/src/thundersvm/syncmem.cpp:29:17: note: in expansion of macro ‘CUDA_CHECK’
>                  CUDA_CHECK(cudaFree(device_ptr));
>                  ^~~~~~~~~~


When I try to import thunderSVM this error shows up:

> >>> from thundersvm import SVC
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/jguzek/.local/lib/python3.6/site-packages/thundersvm/__init__.py", line 12, in <module>
>     from .thundersvm import *
>   File "/home/jguzek/.local/lib/python3.6/site-packages/thundersvm/thundersvm.py", line 41, in <module>
>     thundersvm = CDLL(lib_path)
>   File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: libcusparse.so.9.0: cannot open shared object file: No such file or directory
> >>> exit()

I think this might indicate that it wants CUDA 9.0.

I used `cmake -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6 ..` if it somehow varies

**Comment by zeyiwen** [comment]
We would like to close this issue to reduce the risk of confusion. We will definitely look into the potential problems in the space of execution environment settings.
