### ISSUE TITLE
get_coef has off by one error

### ISSUE THREAD

**Issue by Palpatineli** [Xtra-Computing/thundersvm#147]
After fitting a model model.coef_ looks wrong. The last dimension will always be 0 and if you compare that to the coef_ from sklearn's SVC you will see that it's all shifted by one. For example, in one of the runs I have:
```
from thundersvm import SVC as tSVC
from sklearn.svm import SVC as kSVC
k_svc = kSVC(kernel='linear', gamma=1E-7, C=1)
t_svc = tSVC(kernel='linear', gamma=1E-7, C=1)
k_svc.fit(X, y)
t_svc.fit(X, y)
```
In[9]:     k_svc.coef_
Out[9]:
array([[ 1.32950959,  0.97228444, -2.16840056,  2.30751586,  0.12430373,
         0.24256619,  1.91916157, -1.14547476,  0.92084549, -1.0261113 ]])
In[11]:     k_svc.intercept_
Out[11]: array([0.10570043])

In[10]:     t_svc.coef_
Out[10]:
array([[ 0.97205472, -2.16802955,  2.3074162 ,  0.12444011,  0.24210396,
         1.91905808, -1.14513373,  0.92070591, -1.02566159,  0.        ]])
In[12]:     t_svc.intercept_
Out[12]: array([-0.10579848])

Otherwise both models predict the same results.
I went into the thundernsvmScikit.py file and found that the c funciton thundersvm.get_coef already gives the off-by-1 result.

If this is intentional, how do I recover the coefficients, if it's not, can you fix that?

**Comment by jiahuanluo** [comment]
Hi @Palpatineli,

Could you please share a subset of your dataset and script? They will help us fix this efficiently.

**Comment by Palpatineli** [comment]
Hi @jiahuanluo, I have tried it on an artificial set and the same errors appear:
```
from thundersvm import SVC
np.random.seed(12345)
coef = np.random.randn(11)
X = np.random.randn(100, 10)
y = (X.dot(coef[0: 10, np.newaxis]) > -coef[10]).ravel() * 2 - 1
svc = SVC(kernel='linear', gamma=1E-5, C=1)
svc.fit(X, y)
print(svc.coef_)
```
and it prints:
In[8]:     print(svc.coef_)
[[-0.3202174   0.19284329  0.04366636 -1.92630565 -1.4033004  -0.46049836
  -0.06861141 -1.01132667 -1.38034987  0.        ]]

while the same X and y with sklearn SVC gives:

`kSVC(kernel='linear', gamma=1E-5, C=1).fit(X, y).coef_`

array([[-0.24643811,  0.31998003, -0.19304263, -0.04345196,  1.9264185 ,
         1.4027516 ,  0.46053458,  0.06927284,  1.011293  ,  1.38041789]])

**Comment by GODqinbin** [comment]
Hi @Palpatineli 

Please update the code to the latest version. This bug existed in your version but we fixed it later. I have tried your code in the latest library and it works fine. Thanks.
