### ISSUE TITLE
std::bad_alloc when loading from file using Python interface

### ISSUE THREAD

**Issue by yuxhuang** [Xtra-Computing/thundersvm#148]
Hi,

I have a consistently reproducible `std::bad_alloc` error when trying to load a trained model `SVC().load_from_file('/path/to/model')`.  On Windows,

```
  File "path\to\thundersvm.py", line 473, in load_from_file
    thundersvm.get_sv(csr_row, csr_col, csr_data, data_size, c_void_p(self.model))
OSError: exception: access violation reading 0x00000000000000AB
```

And on Linux,
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

On both Windows and Linux, I built the code from your `master` branch with CUDA 10.0.

Attached is the model file that causes the error.
[SVC.zip](https://github.com/Xtra-Computing/thundersvm/files/3175949/SVC.zip)

**Comment by GODqinbin** [comment]
Hi @yuxhuang 

Thanks for your feedback. We have fixed this bug. You can update the library and try again.

**Comment by yuxhuang** [comment]
@GODqinbin thanks, it works fine now. Much appreciated.
