### ISSUE TITLE
make uninstall doesn't work

### ISSUE THREAD

**Issue by Gunnvant** [Xtra-Computing/thundersvm#153]
I have built from source on an ubuntu machine. I wanted to remove this package, but make uninstall is not working.
How can this package be removed?

**Comment by GODqinbin** [comment]
By default, CMake does not provide the "make uninstall" target. If you use the following instructions to build Thundersvm:
`mkdir build && cd build && cmake .. && make -j`
You can just delete the 'build' directory to remove it.

**Comment by Gunnvant** [comment]
I removed the build directory, but I am still able to access thundersvm via python api, ideally after removing build directory,I should not be able to run python api. I can also see my gpu memory being consumed when I run thundersvm via python interface after removing the build directory

**Comment by GODqinbin** [comment]
If you have installed thundersvm via python, you can remove it by
`pip uninstall thundersvm`

**Comment by Gunnvant** [comment]
thanks
