### ISSUE TITLE
gpuid seems not to work

### ISSUE THREAD

**Issue by samieti02** [Xtra-Computing/thundersvm#156]
Hello dear Sir,

I tried to set differents values for gpuid in SVM like

SVM( gpuid =1  ) Or SVM( gpuid =2 ), but the process still proceed on gpu 0. Although the computer has 2 Tesla cards.

Can you please help me with that?

Sami

**Comment by GODqinbin** [comment]
Hi, @samieti02 

We have tried ThunderSVM on a computer with 2 Tesla GPUs and gpuid works fine. The process should run on gpu 1 if you set gpuid=1. The function cudaSetDevice() is used to set the gpu. Maybe the function doesn't work for your gpu configuration.  Can you provide more details?

**Comment by samieti02** [comment]
Hi @GODqinbin ,

Thanks for the reply, The problem occurred when we passed the arguments through the console. 
It is now fixed.

thanks
