### ISSUE TITLE
How to trace Segmentation fault ?

### ISSUE THREAD

**Issue by budim12** [Xtra-Computing/thundersvm#167]
I just write my code, input using text and use tfidf tokenizing..

![Screenshot from 2019-09-16 12-06-35_](https://user-images.githubusercontent.com/45816145/64935370-17008d80-d87b-11e9-9fb8-946cf3750c04.png)

How to trace it ?

**Comment by GODqinbin** [comment]
A possible solution is to use [valgrind](http://www.valgrind.org/). Or you can provide the script or dataset for us to reproduce the issue and fix it.
