### ISSUE TITLE
Non-sparse formats

### ISSUE THREAD

**Issue by beevabeeva** [Xtra-Computing/thundersvm#170]
Hi,

I have been planning to use ThunderSVM (and ThunderGBM) in my research.
Briefly, this research consists of implementing state of the art GPU algorithms in the [ATM](https://github.com/HDI-Project/ATM) framework.
The ATM framework uses non-sparse matrix as the input format.
I have posted an [issue](https://github.com/HDI-Project/ATM/issues/155) regarding this on their repo too.
I know that your work is based on LIBSVM and that the input format is somewhat of a contentious issue.
But my question is:
How difficult would it be to implement support for non-sparse/LIBSVM input formats?
In particular, ATM expects input in the form:
```
feature_01,feature_02,feature_03,feature_04,class
5.1,3.5,1.4,0.2,Iris-setosa
4.9,3.0,1.4,0.2,Iris-setosa
4.7,3.2,1.3,0.2,Iris-setosa
4.6,3.1,1.5,0.2,Iris-setosa
```

- It uses a single comma, ,, as the separator.
- Its first row is a header that contains the names of the columns.
- There is a column that contains the target variable that will need to be predicted.
- The rest of the columns are all variables or features that will be used to predict the target column.
- Each row corresponds to a single, complete, training sample.
(see [this page](https://hdi-project.github.io/ATM/#data-format) )

Thanks,

Avi

**Comment by zeyiwen** [comment]
A parser for the data format you have mentioned will be needed. You are more than welcome to contribute.
