### ISSUE TITLE
The link of whl file for windows is invalid

### ISSUE THREAD

**Issue by wenlibin02** [Xtra-Computing/thundersvm#174]
Hi, 
I cannot download the .whl file from 
https://www.comp.nus.edu.sg/~wenzy/pip-pack/svm/thundersvm-cu10-0.2.0-py3-none-win_amd64.whl

Why not just place the binary files in release?

Thanks for your help.

**Comment by zeyiwen** [comment]
We will upload the whl files to the repo.

**Comment by zeyiwen** [comment]
The links are updated. Please find the file under ``python/dist/`` of this repository.
