### ISSUE TITLE
shell script version of grid.py

### ISSUE THREAD

**Issue by WeiChihChern** [Xtra-Computing/thundersvm#178]
I used the scripts as suggested from the main page.

I wonder how can I get the recommended parameters as libSVM's grid.py does?

Thank you.

**Comment by zeyiwen** [comment]
I am not sure if I understood your question correctly. Perhaps our documentation on grid search might be useful for you. Please take a look [here](https://github.com/Xtra-Computing/thundersvm/blob/master/docs/how-to.md#how-can-i-do-grid-search).

**Comment by WeiChihChern** [comment]
@zeyiwen Thanks for answering. My question is when doing the grid search via a shell scrip as described in your documentation.  
```
#!/usr/bin/bash
DATASET=$1
OPTIONS=
N_FOLD=5
for c in 1 3 10 30 100
do
  for g in 0.1 0.3 1 3 10
    do
      bin/thundersvm-train -c ${c} -g ${g} -v ${N_FOLD} ${OPTIONS} ${DATASET}
    done
done
```
Will the binary generate any log file indicating best c & g parameters for training? After running the script I only received a message show `Cross Accuracy = xxxx`. 

Thank you.

**Comment by zeyiwen** [comment]
You can use ``bash`` to print out ``c`` and ``g`` together with the accuracy, and then write a script to obtain the best ``c`` and ``g``.

It would be awesome if you can implement this functionality and share it to the ThunderSVM community.

**Comment by WeiChihChern** [comment]
@zeyiwen Got it, I thought this had been implemented already and I was just looking for any documentation on how to use it correctly.

I will try and issue a pull request if the result is satisfying.
