### ISSUE TITLE
brew install thundersvm

### ISSUE THREAD

**Issue by ankane** [Xtra-Computing/thundersvm#182]
Hi, I created a Homebrew formula for ThunderSVM (https://github.com/Homebrew/homebrew-core/pull/47144) to make installation easier on Mac, so users will be able to do:

```sh
brew install thundersvm
```

Typically, formula are expected to compile with Clang to be accepted by Homebrew, so I wanted to get your thoughts on including this. I was able to get it to compile with the following steps:

Install OpenMP

```sh
brew install openmp
```

Add to `src/thundersvm/CMakeLists.txt` (following pattern from [LightGBM](https://github.com/microsoft/LightGBM/blob/16c551c13d49c03fd4d871418257b1d89569d95b/CMakeLists.txt#L226) and [this resource](https://cliutils.gitlab.io/modern-cmake/chapters/packages/OpenMP.html))

```txt
TARGET_LINK_LIBRARIES(thundersvm OpenMP::OpenMP_CXX)
```

Install ThunderSVM

```sh
git clone --recursive https://github.com/Xtra-Computing/thundersvm
cd thundersvm
mkdir build
cd build
cmake .. -DUSE_CUDA=OFF -DUSE_EIGEN=ON -DOpenMP_C_FLAGS="-Xpreprocessor -fopenmp -I/usr/local/opt/libomp/include" -DOpenMP_C_LIB_NAMES=omp -DOpenMP_CXX_FLAGS="-Xpreprocessor -fopenmp -I/usr/local/opt/libomp/include" -DOpenMP_CXX_LIB_NAMES=omp -DOpenMP_omp_LIBRARY=/usr/local/opt/libomp/lib/libomp.dylib
make
```

Related issue: #39

Also, on the topic of easier installation, it'd be great if there was a `make install` task that installed the binary files and shared library.

Let me know what you think. Thanks!

**Comment by zeyiwen** [comment]
Thank you Andrew for the great work! Would you please write the instructions to Mac installation docs (e.g., [here](https://github.com/Xtra-Computing/thundersvm/blob/master/docs/get-started.md#installation-for-macos)) and make a pull request? I can merge it.

**Comment by zeyiwen** [comment]
Thank you for the work. I have merged the PR, and like to close this issue.

**Comment by ankane** [comment]
Just fyi, I figured out the Homebrew issue, so will submit a PR to Homebrew once a new version is out.

**Comment by zeyiwen** [comment]
Thanks! We are looking forward to it.
