### ISSUE TITLE
Missing environment variable 'BUILD_TAG' when installing Python module

### ISSUE THREAD

**Issue by BramVanroy** [Xtra-Computing/thundersvm#188]
After successfully building the library on Linux, I also try to install the Python module on Python 3.7 using the installation guide. Unfortunately, that does not seem to work:

```
Traceback (most recent call last):
  File "setup.py", line 29, in <module>
    setuptools.setup(name="thundersvm" + os.environ['BUILD_TAG'],
  File "/home/bram/.local/share/virtualenvs/semeval-task7-agI68AXG/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'BUILD_TAG'
```

**Comment by shijiashuai** [comment]
It's a bug here. But if you just need the python library, you can try the pre-built ones. Download whl file for your platform in this [https://github.com/Xtra-Computing/thundersvm/releases/tag/v0.3.4](link), and then run `pip install xxx.whl`

Or you can temporarily change line 29 in `setup.py` into `setuptools.setup(name="thundersvm", ` and install again.

Will fix it soon.

**Comment by BramVanroy** [comment]
Unfortunately you only have wheels for Python 3.6 and CUDA 10. I need to build it for 3.7 and 10.1 respectively.

So I can just remove ` + os.environ['BUILD_TAG']` in the setup file?

**Comment by zeyiwen** [comment]
Yes, you can. This part of info is optional, and removing it does not affect your wheel file except the naming.

**Comment by BramVanroy** [comment]
Okay, thanks. I'll leave this open until a fix is implemented.

**Comment by shijiashuai** [comment]
This issue should have been fixed, so I would like to close it.
