### ISSUE TITLE
Thumdersvm. dll - dependent dynamic library. 

### ISSUE THREAD

**Issue by 1113571287** [Xtra-Computing/thundersvm#190]
My project found the tumdersvm.dll file correctly, but does it need to import the other VC's dynamic library?   My error is   in fit thundersvm.get_sv(csr_row, csr_col, csr_data, data_size, sv_indices, c_void_p(self.model))
OSError: [WinError -529697949] Windows Error 0xe06d7363

**Comment by zeyiwen** [comment]
No other DLL files are needed. You can try to run thundersvm directly from visual studio. If your environment is not properly set up, you should be able to see some error messages there.

**Comment by 1113571287** [comment]
Thanks
