### ISSUE TITLE
Who has the wheel file for CUDA10 under the Linux system 

### ISSUE THREAD

**Issue by 1113571287** [Xtra-Computing/thundersvm#192]

**Comment by zeyiwen** [comment]
This [link](https://github.com/Xtra-Computing/thundersvm/releases) has prebuilt wheel files. Please check it out. [Here](https://github.com/Xtra-Computing/thundersvm/blob/master/docs/how-to.md#build-python-wheel-file) is the instruction for building your own wheel file.

**Comment by 1113571287** [comment]
> 
> 
> This [link](https://github.com/Xtra-Computing/thundersvm/releases) has prebuilt wheel files. Please check it out. [Here](https://github.com/Xtra-Computing/thundersvm/blob/master/docs/how-to.md#build-python-wheel-file) is the instruction for building your own wheel file.



> 
> 
> This [link](https://github.com/Xtra-Computing/thundersvm/releases) has prebuilt wheel files. Please check it out. [Here](https://github.com/Xtra-Computing/thundersvm/blob/master/docs/how-to.md#build-python-wheel-file) is the instruction for building your own wheel file.

Thank you very much
