### ISSUE TITLE
Possible to build linux python 3.7 and 3.8 wheels in travis CI?

### ISSUE THREAD

**Issue by guillaumedsde** [Xtra-Computing/thundersvm#205]
Hi, I've tried to mess around the [travisCI config in my own branch of the repo](https://github.com/guillaumedsde/thundersvm/blob/master/.travis.yml#L47)  but I've not managed to get travis to build linux python 3.7 and 3.8 wheels, for some reason it only builds python3.6 does anyone know why? I feel like I'm misunderstanding Travis' include syntax

**Comment by zeyiwen** [comment]
Sorry for the delay. Our team is rather busy recently, due to proposal and paper deadlines along with the teaching load. We will get back to this issue as soon as we can.

**Comment by guillaumedsde** [comment]
Hi @zeyiwen I've dived into the Travis config some more and have managed to build more wheels, I've submitted a PR: https://github.com/Xtra-Computing/thundersvm/pull/209

**Comment by zeyiwen** [comment]
PR merged. Thanks.
