### ISSUE TITLE
question about timing measurement

### ISSUE THREAD

**Issue by jinz2014** [Xtra-Computing/thundersvm#212]
In the quick start, you show the command to train and predict using the test dataset:

./bin/thundersvm-train -c 100 -g 0.5 ../dataset/test_dataset.txt
./bin/thundersvm-predict ../dataset/test_dataset.txt test_dataset.txt.model test_dataset.predict

I would like to measure (benchmark) the time of training and prediction using all the dataset users can download through your script, but I don't know what parameter values I should use for timing measurement on a CPU and GPU. Can you explain how you measure the training/prediction time on a CPU and a GPU ? Can you list the values of the parameters people should use for each dataset to obtain reasonable timing results ?  Can you suggest the command-line options people should use for your dataset ?

Thank you

**Comment by zeyiwen** [comment]
You need to add timers in the code to measure the time in different components.

**Comment by jinz2014** [comment]
I'd like to reopen the issue because it is not solved to my understanding.  For the test data set, you used -c 100 -g 0.5. Can you please list the (common) parameters values for other datasets available from your repository ?
