### ISSUE TITLE
SVC linear kernel missing coef_ in save and load

### ISSUE THREAD

**Issue by AtlantixJJ** [Xtra-Computing/thundersvm#215]
Hi, I found that when I save a trained SVC to file and reload it, the coef_ attribute is missing.

According to the code line 486 - 490 in `thundersvm.py`, model loading for linear kernel are commented, preventing the model from loading linear coef. See https://github.com/Xtra-Computing/thundersvm/blob/d3f3906efe33e979fc9a169ab57c5886ffa103bd/python/thundersvm/thundersvm.py#L486 .

Would you please take a look at this? This makes it impossible to reload a SVC linear.

**Comment by GODqinbin** [comment]
Hi @AtlantixJJ ,

We have fixed this issue. Now you should be able to load the coef_ successfully. You can update the library and try again. Thanks.
