### ISSUE TITLE
Return 0-1 value for classification? 

### ISSUE THREAD

**Issue by antithing** [Xtra-Computing/thundersvm#216]
Hi, I am looking for a way to classify intensity of facial expressions by passing normalized landmark points into an SVM.

Using this code, can I then return the intensity, or zero to one value of each class? 

Thanks!

**Comment by zeyiwen** [comment]
Please try the ``-b`` option in [parameter](https://github.com/Xtra-Computing/thundersvm/blob/master/docs/parameters.md) page.

Otherwise, you need to obtain the raw values of ThunderSVM in the C++ code, before the conversion into labels. You are more than welcome to contribute a new interface to this project.

**Comment by antithing** [comment]
Thank you. I will look into using the SVR option.

For this, should my input data have intensity values as well as binary classification?

**Comment by antithing** [comment]
Hi @zeyiwen , I have my data prepared, and i am training a model using:

`thundersvm-train -s 1 -c 100 -b 1 -g 0.5 data.csv`

This trains well, and when i predict with:

`thundersvm-predict data.csv data.csv.model data.csv.predict`

I get a file with the labels and probabilities.
```

2020-05-10 18:46:00,719 INFO [default] loading dataset from file "data.csv"
2020-05-10 18:46:00,727 INFO [default] #instances = 57, #features = 36
2020-05-10 18:46:00,980 INFO [default] predict with probability
2020-05-10 18:46:00,992 INFO [default] Accuracy = 0.947368


labels 0 1 2 
0 0.874525 0.0890417 0.0364336 
0 0.982203 0.00396966 0.0138274 
0 0.835266 0.0798462 0.0848874 
0 0.844447 0.115121 0.040432 
.... etc

```

Great! My question is, what can i adjust to increase the accuracy? Is it possible to get up to 99% or more?

Thank you again for your amazing work!

**Comment by zeyiwen** [comment]
These are some general questions on hyperparameter tuning and data preprocessing. Let's keep the forum for ThunderSVM related discussions.
