### ISSUE TITLE
What does `diff` mean in verbose information?

### ISSUE THREAD

**Issue by AtlantixJJ** [Xtra-Computing/thundersvm#217]
Hi, I tried to look up in documentation and in the code but I am still unable to interpret the number of the verbose information. As I am training a really large model and want to know the approximate progress and remaining time based on the verbose information.

An example:

```
2020-05-05 16:50:25,552 INFO [default] global iter = 3900, total local iter = 477699, diff = 62.3235
```

BTW, what is the approximate time for a binary classification problem with (1_000_000, 1000) data size?

**Comment by zeyiwen** [comment]
Diff represents the dual gap.
