### ISSUE TITLE
Could you make a release?

### ISSUE THREAD

**Issue by hubutui** [Xtra-Computing/thundersvm#221]
It seems that you update thundersvm to 0.3.12 in [pypi](https://pypi.org/project/thundersvm/#history), but the latest release in [github](https://github.com/Xtra-Computing/thundersvm/releases) is 0.3.4. Could you keep them up to date? You might wanna make a consistent tag in https://github.com/Xtra-Computing/thundersvm/tags.

**Comment by zeyiwen** [comment]
The PyPI version should be 0.3.4. I haven't found out why the version number becomes 0.3.12. Please feel free to use the 0.3.4 release on GitHub.
