### ISSUE TITLE
Is it possible to build the gpu version on a CPU-only device?

### ISSUE THREAD

**Issue by xraywu** [Xtra-Computing/thundersvm#224]
Hi there, I am trying to build a Docker image with the linux GPU version from source. The problem is that the building machine only has CPU (which is usually the case for a general CI environment), but it gives the below error, even if CUDA is already installed in the base Docker image.

```
Compile with CUDA
CMake Error at FindCUDA.cmake:700 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  CMakeLists.txt:39 (find_package)
```

Is it possible to build the Docker image on a CPU only device and then run on one with GPU?

**Comment by zeyiwen** [comment]
Yes. This is not a question related to ThunderSVM though...
