### ISSUE TITLE
identifier "cusparseScsrmm2" is undefined

### ISSUE THREAD

**Issue by dreldrel** [Xtra-Computing/thundersvm#227]
Hi guys,
I face the error called "identifier "cusparseScsrmm2" is undefined" when I build the solution inside Visual Studio. How do I solve the problem? I found that cusparseScsrmm2 is deprecated in CUDA 11.

![image](https://user-images.githubusercontent.com/45089360/90959154-c6060a00-e4cb-11ea-9123-54c0ae6cc91d.png)

**Comment by zeyiwen** [comment]
This issue should be fixed now. Please reopen it if you still have the problems.
