### ISSUE TITLE
Error with "make -j"

### ISSUE THREAD

**Issue by vkverma01** [Xtra-Computing/thundersvm#40]
# cse@ubuntu:~/thundersvm/build$ sudo cmake -DUSE_CUDA=ON -DUSE_EIGEN=OFF ..
-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
Compile with CUDA
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cse/thundersvm/build

# cse@ubuntu:~/thundersvm/build$ sudo make -j
[  1%] Building NVCC (Device) object src/thundersvm/CMakeFiles/thundersvm-train.dir/kernel/thundersvm-train_generated_smo_kernel.cu.o
Scanning dependencies of target googletest
[  2%] Building NVCC (Device) object src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_kernelmatrix_kernel.cu.o
[  3%] Building NVCC (Device) object src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_smo_kernel.cu.o
[  5%] Building NVCC (Device) object src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_kernelmatrix_kernel.cu.o
[  6%] Building NVCC (Device) object src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_smo_kernel.cu.o
[  7%] Building NVCC (Device) object src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_kernelmatrix_kernel.cu.o
[  8%] Building NVCC (Device) object src/thundersvm/CMakeFiles/thundersvm-predict.dir/kernel/thundersvm-predict_generated_kernelmatrix_kernel.cu.o
[ 10%] Building NVCC (Device) object src/thundersvm/CMakeFiles/thundersvm-train.dir/kernel/thundersvm-train_generated_kernelmatrix_kernel.cu.o
[ 11%] Building NVCC (Device) object src/thundersvm/CMakeFiles/thundersvm-predict.dir/kernel/thundersvm-predict_generated_smo_kernel.cu.o
[ 12%] Building NVCC (Device) object src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_smo_kernel.cu.o
[ 13%] Creating directories for 'googletest'
[ 15%] Performing download step (git clone) for 'googletest'
Cloning into 'googletest'...
Error copying file (if different) from "/home/cse/thundersvm/build/src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_kernelmatrix_kernel.cu.o.depend.tmp" to "/home/cse/thundersvm/build/src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_kernelmatrix_kernel.cu.o.depend".
CMake Error at thundersvm_generated_kernelmatrix_kernel.cu.o.cmake:232 (message):
  Error generating
  /home/cse/thundersvm/build/src/thundersvm/CMakeFiles/thundersvm.dir/kernel/./thundersvm_generated_kernelmatrix_kernel.cu.o

src/thundersvm/CMakeFiles/thundersvm.dir/build.make:70: recipe for target 'src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_kernelmatrix_kernel.cu.o' failed
make[2]: *** [src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_kernelmatrix_kernel.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/cse/thundersvm/include/thundersvm/util/log.h(1323): warning: call of pure virtual function

/home/cse/thundersvm/include/thundersvm/util/log.h(1323): warning: call of pure virtual function

/home/cse/thundersvm/include/thundersvm/util/log.h(1323): warning: call of pure virtual function

/home/cse/thundersvm/include/thundersvm/util/log.h(1323): warning: call of pure virtual function

/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
Already on 'master'
Your branch is up-to-date with 'origin/master'.
[ 16%] No patch step for 'googletest'
[ 17%] Performing update step for 'googletest'
CMake Error at thundersvm_generated_kernelmatrix_kernel.cu.o.cmake:266 (message):
  Error generating file
  /home/cse/thundersvm/build/src/thundersvm/CMakeFiles/thundersvm.dir/kernel/./thundersvm_generated_kernelmatrix_kernel.cu.o

src/thundersvm/CMakeFiles/thundersvm-predict.dir/build.make:70: recipe for target 'src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_kernelmatrix_kernel.cu.o' failed
make[2]: *** [src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_kernelmatrix_kernel.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/cse/thundersvm/include/thundersvm/util/log.h(1323): warning: call of pure virtual function

/home/cse/thundersvm/include/thundersvm/util/log.h(1323): warning: call of pure virtual function

/home/cse/thundersvm/include/thundersvm/util/log.h(1323): warning: call of pure virtual function

/home/cse/thundersvm/include/thundersvm/util/log.h(1323): warning: call of pure virtual function

/home/cse/thundersvm/include/thundersvm/util/log.h(1323): warning: call of pure virtual function

CMake Error at thundersvm_generated_kernelmatrix_kernel.cu.o.cmake:266 (message):
  Error generating file
  /home/cse/thundersvm/build/src/thundersvm/CMakeFiles/thundersvm.dir/kernel/./thundersvm_generated_kernelmatrix_kernel.cu.o

src/thundersvm/CMakeFiles/thundersvm-train.dir/build.make:70: recipe for target 'src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_kernelmatrix_kernel.cu.o' failed
make[2]: *** [src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_kernelmatrix_kernel.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMake Error at thundersvm-predict_generated_kernelmatrix_kernel.cu.o.cmake:266 (message):
  Error generating file
  /home/cse/thundersvm/build/src/thundersvm/CMakeFiles/thundersvm-predict.dir/kernel/./thundersvm-predict_generated_kernelmatrix_kernel.cu.o

src/thundersvm/CMakeFiles/thundersvm-predict.dir/build.make:84: recipe for target 'src/thundersvm/CMakeFiles/thundersvm-predict.dir/kernel/thundersvm-predict_generated_kernelmatrix_kernel.cu.o' failed
make[2]: *** [src/thundersvm/CMakeFiles/thundersvm-predict.dir/kernel/thundersvm-predict_generated_kernelmatrix_kernel.cu.o] Error 1
CMake Error at thundersvm-train_generated_kernelmatrix_kernel.cu.o.cmake:266 (message):
  Error generating file
  /home/cse/thundersvm/build/src/thundersvm/CMakeFiles/thundersvm-train.dir/kernel/./thundersvm-train_generated_kernelmatrix_kernel.cu.o

src/thundersvm/CMakeFiles/thundersvm-train.dir/build.make:84: recipe for target 'src/thundersvm/CMakeFiles/thundersvm-train.dir/kernel/thundersvm-train_generated_kernelmatrix_kernel.cu.o' failed
make[2]: *** [src/thundersvm/CMakeFiles/thundersvm-train.dir/kernel/thundersvm-train_generated_kernelmatrix_kernel.cu.o] Error 1
Current branch master is up to date.
[ 18%] Performing configure step for 'googletest'
-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG
    CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE
    CMAKE_C_COMPILIER

-- Build files have been written to: /home/cse/thundersvm/build/src/test/gtest/src/googletest-build
[ 20%] Performing build step for 'googletest'
Scanning dependencies of target gmock
Scanning dependencies of target gtest
Scanning dependencies of target gmock_main
[  9%] Building CXX object googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[ 18%] Building CXX object googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o
[ 27%] Building CXX object googlemock/CMakeFiles/gmock.dir/__/googletest/src/gtest-all.cc.o
[ 36%] Building CXX object googlemock/CMakeFiles/gmock_main.dir/src/gmock_main.cc.o
[ 54%] Building CXX object googlemock/CMakeFiles/gmock_main.dir/__/googletest/src/gtest-all.cc.o
[ 54%] Building CXX object googlemock/CMakeFiles/gmock_main.dir/src/gmock-all.cc.o
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
[ 63%] Linking CXX static library libgmock.a
[ 72%] Linking CXX static library libgtest.a
[ 72%] Built target gmock
[ 81%] Linking CXX static library libgmock_main.a
[ 81%] Built target gtest
Scanning dependencies of target gtest_main
[ 90%] Building CXX object googlemock/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[ 90%] Built target gmock_main
CMake Error at thundersvm-train_generated_smo_kernel.cu.o.cmake:266 (message):
  Error generating file
  /home/cse/thundersvm/build/src/thundersvm/CMakeFiles/thundersvm-train.dir/kernel/./thundersvm-train_generated_smo_kernel.cu.o

src/thundersvm/CMakeFiles/thundersvm-train.dir/build.make:77: recipe for target 'src/thundersvm/CMakeFiles/thundersvm-train.dir/kernel/thundersvm-train_generated_smo_kernel.cu.o' failed
make[2]: *** [src/thundersvm/CMakeFiles/thundersvm-train.dir/kernel/thundersvm-train_generated_smo_kernel.cu.o] Error 1
[100%] Linking CXX static library libgtest_main.a
[100%] Built target gtest_main
[ 21%] No install step for 'googletest'
[ 22%] Completed 'googletest'
[ 22%] Built target googletest
CMake Error at thundersvm_generated_smo_kernel.cu.o.cmake:266 (message):
  Error generating file
  /home/cse/thundersvm/build/src/thundersvm/CMakeFiles/thundersvm.dir/kernel/./thundersvm_generated_smo_kernel.cu.o

src/thundersvm/CMakeFiles/thundersvm-predict.dir/build.make:63: recipe for target 'src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_smo_kernel.cu.o' failed
make[2]: *** [src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_smo_kernel.cu.o] Error 1
CMake Error at thundersvm_generated_smo_kernel.cu.o.cmake:266 (message):
  Error generating file
  /home/cse/thundersvm/build/src/thundersvm/CMakeFiles/thundersvm.dir/kernel/./thundersvm_generated_smo_kernel.cu.o

src/thundersvm/CMakeFiles/thundersvm-train.dir/build.make:63: recipe for target 'src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_smo_kernel.cu.o' failed
make[2]: *** [src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_smo_kernel.cu.o] Error 1
CMakeFiles/Makefile2:158: recipe for target 'src/thundersvm/CMakeFiles/thundersvm-train.dir/all' failed
make[1]: *** [src/thundersvm/CMakeFiles/thundersvm-train.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMake Error at thundersvm-predict_generated_smo_kernel.cu.o.cmake:266 (message):
  Error generating file
  /home/cse/thundersvm/build/src/thundersvm/CMakeFiles/thundersvm-predict.dir/kernel/./thundersvm-predict_generated_smo_kernel.cu.o

src/thundersvm/CMakeFiles/thundersvm-predict.dir/build.make:77: recipe for target 'src/thundersvm/CMakeFiles/thundersvm-predict.dir/kernel/thundersvm-predict_generated_smo_kernel.cu.o' failed
make[2]: *** [src/thundersvm/CMakeFiles/thundersvm-predict.dir/kernel/thundersvm-predict_generated_smo_kernel.cu.o] Error 1
CMakeFiles/Makefile2:195: recipe for target 'src/thundersvm/CMakeFiles/thundersvm-predict.dir/all' failed
make[1]: *** [src/thundersvm/CMakeFiles/thundersvm-predict.dir/all] Error 2
CMake Error at thundersvm_generated_smo_kernel.cu.o.cmake:266 (message):
  Error generating file
  /home/cse/thundersvm/build/src/thundersvm/CMakeFiles/thundersvm.dir/kernel/./thundersvm_generated_smo_kernel.cu.o

src/thundersvm/CMakeFiles/thundersvm.dir/build.make:63: recipe for target 'src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_smo_kernel.cu.o' failed
make[2]: *** [src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_smo_kernel.cu.o] Error 1
CMakeFiles/Makefile2:121: recipe for target 'src/thundersvm/CMakeFiles/thundersvm.dir/all' failed
make[1]: *** [src/thundersvm/CMakeFiles/thundersvm.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by shijiashuai** [comment]
There could be some problems when parallel compiling. You can try `make` instread of `make -j`.

**Comment by vkverma01** [comment]
**After Compiling successfully I tried the make  but getting the following error.**

**cse@ubuntu:~/thundersvm/build$ sudo make** 
[  1%] Building NVCC (Device) object src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_kernelmatrix_kernel.cu.o
/home/cse/thundersvm/include/thundersvm/util/log.h(1323): warning: call of pure virtual function

/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
CMake Error at thundersvm_generated_kernelmatrix_kernel.cu.o.cmake:266 (message):
  Error generating file
  /home/cse/thundersvm/build/src/thundersvm/CMakeFiles/thundersvm.dir/kernel/./thundersvm_generated_kernelmatrix_kernel.cu.o


src/thundersvm/CMakeFiles/thundersvm.dir/build.make:70: recipe for target 'src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_kernelmatrix_kernel.cu.o' failed
make[2]: *** [src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_kernelmatrix_kernel.cu.o] Error 1
CMakeFiles/Makefile2:121: recipe for target 'src/thundersvm/CMakeFiles/thundersvm.dir/all' failed
make[1]: *** [src/thundersvm/CMakeFiles/thundersvm.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by shijiashuai** [comment]
This error comes from CUDA 7.5. I've just updated `CMakeLists.txt` as suggested in #34.

**Comment by vkverma01** [comment]
Thanks a lot ..I changed the CUDA 7.5 to CUDA 8.0 it works.
But still only **make** command is working.
**make -j** is not working

**Comment by thomaskisler** [comment]
I have the same issue, make without parallelization is working.
