### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by julianofoleiss** [Xtra-Computing/thundersvm#52]
I noticed that while thundersvm is running, it usually keeps a cpu core at 100%. Why is this?

Is there any busy waiting for the GPU? Calculations that cannot be done directly in the GPU? Data transfer?

Thanks!

**Comment by zeyiwen** [comment]
ThunderSVM (GPU) also needs the CPU for training data parsing and GPU task scheduling, so the scenario you have seen is normal.
