### ISSUE TITLE
ThunderSVM GCC 6 or later

### ISSUE THREAD

**Issue by rdevon** [Xtra-Computing/thundersvm#54]
Ubuntu 17.10
cuda 9.1 (installed with .deb)

Error occurs with or without -j in make:

```
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at /usr/share/cmake-3.9/Modules/FindOpenMP.cmake:200 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "c" will no longer be dereferenced when the policy is
  set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  /usr/share/cmake-3.9/Modules/FindOpenMP.cmake:324 (_OPENMP_GET_FLAGS)
  CMakeLists.txt:26 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

Compile with CUDA
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/devon/Code/thundersvm/build
[  3%] Building NVCC (Device) object src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_smo_kernel.cu.o
In file included from /usr/local/cuda/include/host_config.h:50:0,
                 from /usr/local/cuda/include/cuda_runtime.h:78,
                 from <command-line>:0:
/usr/local/cuda/include/crt/host_config.h:121:2: error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!
 #error -- unsupported GNU version! gcc versions later than 6 are not supported!
  ^~~~~
CMake Error at thundersvm_generated_smo_kernel.cu.o.Release.cmake:222 (message):
  Error generating
  /home/devon/Code/thundersvm/build/src/thundersvm/CMakeFiles/thundersvm.dir/kernel/./thundersvm_generated_smo_kernel.cu.o


src/thundersvm/CMakeFiles/thundersvm.dir/build.make:70: recipe for target 'src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_smo_kernel.cu.o' failed
make[2]: *** [src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_smo_kernel.cu.o] Error 1
CMakeFiles/Makefile2:126: recipe for target 'src/thundersvm/CMakeFiles/thundersvm.dir/all' failed
make[1]: *** [src/thundersvm/CMakeFiles/thundersvm.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by zeyiwen** [comment]
This issue should be due to the compatibility problem of CUDA 9 and GCC 6. You can see [here](https://github.com/ComputationalRadiationPhysics/alpaka/issues/426) for more information.

You may install a lower version of GCC (e.g., gcc 5), and compile the project again.

**Comment by rdevon** [comment]
Actually, GCC 6 (along with G++ 6) works: the problem is with GCC 7. Installing gcc-6 and g++-6, then:
```
export CC=<path to gcc-6>
export CXX=<path to G++-6>
```
before doing cmake seems to work.

**Comment by markroxor** [comment]
Use `cmake -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6 ..` before cmake to specify gcc/g++ compiler.

**Comment by Aurora11111** [comment]
I meet this problem ,and I sloved it just by uninstall old gcc,and reinstall a gcc with verison of 4.9:
1.uninstall gcc
sudo pacman -Rsc gcc
2.reinstall gcc
mkdir -p $HOME/build/
cd $HOME/build/
git clone https://aur.archlinux.org/gcc49.git
cd gcc49
makepkg --syncdeps
sudo pacman --upgrade gcc-4.9.3-1-x86_64.pkg.tar.xz

**Comment by LeeChiuLan** [comment]
I solved it by changing the link of /usr/bin/gcc to gcc-6:
cd /usr/bin
ls -a gcc
-----------------------
lrwxrwxrwx 1 root root 5 Apr   7 02:04 gcc -> gcc-7   # I found the gcc was linked to gcc-7
-----------------------
sudo rm gcc
sudo ln -s gcc-6 gcc
ls -al gcc
gcc --version          #and now is the correct gcc version

**Comment by BramVanroy** [comment]
The comment by @markroxor should probably be in the readme. Changing gcc to a previous version globally is bad practice, but using cmake flags is the way to go.

**Comment by zeyiwen** [comment]
@BramVanroy Thanks. It would be good if you could help us add this to the proper place in the docs. 

We are currently working on paper deadlines. Extremely busy these days.

**Comment by markroxor** [comment]
Please be wary that gcc/g++ is more fundamentally baked in the OS than you might think. Changing it's version just to suit your needs is probably the worst way to tackle the problem. 

@BramVanroy I suggest you add the suggestion to the readme along with the above caveat, if needed.
