### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by rsadek** [Xtra-Computing/thundersvm#96]
Hello!
When I call svm_predict_matlab I get the following error:

Out of memory. Type HELP MEMORY for your options.

Error in svm_train_matlab (line 18)
        calllib('libthundersvm', 'thundersvm_train', length(str2), str2)

But my system and GPU are nowhere near out of memory. What could be causing this issue?
Sometimes instead of the above error I receive the error:

radix_sort: failed to get memory buffer

Any thoughts or suggestions? Thanks!
Ramy

**Comment by GODqinbin** [comment]
Can you share your dataset? So that we can try to reproduce the problem and debug it.
